### PR TITLE
TravisCI support

### PR DESCRIPTION
**Pull request by takacsd**
I created a simple configuration file for Travis CI if you are interested.

Sadly the latest Ubuntu environment is 16.04 on Travis CI and I couldn't make the build work on it, so I had to use docker to have the latest Ubuntu. The downside is that I can't install the necessary perf package there, so the tst_perfparser test is not working.

This is unfortunate, but I think the automatic build is still helpful.

### CODE REVIEW

**Comment by milianw** [comment]
in principle I have no issue with doing this, but at KDAB we host a (non-public) CI that does post-commit compiles and unit test runs.

Before merging this, can you tell me more about the issue with perf? You'll need the packages linux-tools-common and linux-tools-generic, then perf should be available.

**Comment by probonopd** [comment]
Please see https://github.com/KDAB/hotspot/pull/76, I think I managed to compile ot on Travis CI using trusty.

**Comment by takacsd** [comment]
@milianw: AFAIK Perf needs some kernel specific package to work, something like linux-tools-`uname -r`-common or similar. Docker is not a full VM (under Linux), so even the latest ubuntu image will use trusty's kernel on travis, but there is no kernel specific linux-tools package for that old kernel in the repository of zesty.
(If the host is also zesty, it works fine if you starts a privileged docker container.)

My end goal would be to generate packages or something like AppImage for every release, and this PR is just the first step, but if you have this at KDAB already, and you can share it, then it' s even better. ;)

@probonopd: I really like your initiative on AppImage, but I kind of dislike the ppa and the prebuilt stuff in your script. Wouldn't be possible and somewhat cleaner to use docker there too?

**Comment by probonopd** [comment]
@takacsd in which way do you think would using Docker be cleaner? Another option could be using the Open Build Service https://git.io/obs-ai.

**Comment by takacsd** [comment]
@probonopd: Since every dependency is already in the zesty docker image, I thought it is much easier to bundle them, but I did not know that you need to build the AppImage on an old distribution to make it work on lots of distributions.

**Comment by milianw** [comment]
I'm closing this now, as we have merged #76 now. I'm in the process of fixing the travis build.

**Pull request closed without merging**
