### PR TITLE
Add Arch Linux dependency installation command

### PR DESCRIPTION
**Pull request by nilsdeppe**
PS Thanks for the awesome package!

### CODE REVIEW

**Comment by milianw** [comment]
I'm an arch user, but I don't have `qt5ct` installed, I think you rather want to list the deps explicitly - something like `qt5-base qt5-tools`

**Comment by nilsdeppe** [comment]
Do you have the deps at a finer scale? I don't, unfortunately and hopefully understandably don't want to uninstall things just to figure them out. If you have the list I'm happy to edit.

**Comment by milianw** [comment]
It should be just `qt5-base`, amend that and we can take it from there

**Comment by nilsdeppe** [comment]
Awesome, thanks! Just pushed the update.

**Comment by milianw** [comment]
thanks

**Pull request merged**
