### PR TITLE
Adjust to KF6 KNotification API change

### PR DESCRIPTION
**Pull request by kbroulik**
setWidget has been removed in favor of setWindow.

### CODE REVIEW

**Comment by GitMensch** [comment]
This possibly relates to the removal of the original function https://invent.kde.org/frameworks/knotifications/-/merge_requests/123 - but QT6 builds error with

> mainwindow.cpp:158:23: error: ‘class KNotification’ has no member named ‘setWindow‘

because that old PR https://invent.kde.org/frameworks/knotifications/-/merge_requests/16 was only merged recently (1 month ago) so this change is reasonable but the macro used is wrong (not sure if there's actually a usable one yet).

**Comment by milianw** [comment]
@kbroulik ping? can you update the MR please?

**Comment by kbroulik** [comment]
Update to do what?

**Comment by milianw** [comment]
To fix the version check, see the failing test on our Qt6 CI which doesn't yet have this new API apparently:

https://github.com/KDAB/hotspot/actions/runs/6289218537/job/17096541668?pr=511

**Comment by kbroulik** [comment]
Then I suppose your neon is outdated. KF6 has no “version” yet, it’s all git master in-flux.

**Comment by milianw** [comment]
:man_facepalming: thanks for clearing that up, now it's obvious that the error is on our side. I'll see when I get around to update the image and then merge this. Doing so now would break our CI - sorry. I should find the time for that on the weekend I hope.

**Comment by milianw** [comment]
thanks @kbroulik - I updated our docker image for neon, and it works as expected now.

Cheers!

**Pull request merged**
