### PR TITLE
add function to automatically hide all tracepoint columns

### PR DESCRIPTION
**Pull request by lievenhey**
these columns are not interesting since they are only non zero in the
function where the tracepoint is positioned

### CODE REVIEW

**Comment by lievenhey** [comment]
closes #345

**Comment by lievenhey** [comment]
I hope I found all tracepoints, but can you run `sudo perf list | grep Tracepoint | cut -d ":" -f1 | uniq | md5sum` and send me all you tracepoints in case the output is not `22c003cf0b3ade241fadc0d76959c181`

**Comment by lievenhey** [comment]
done. The perfparser provides now a set with all tracepoint derived cost names. This set is used to hide the columns in hideTracepointColumns.

**Review by milianw — CHANGES_REQUESTED** [review]
please hide the _self_ cost, but do keep the _inclusive_ cost as that's useful.

**Comment by lievenhey** [comment]
done

**Comment by milianw** [comment]
thanks, I fixed one minor issue and expanded it a bit.

great work!

**Pull request merged**
