### PR TITLE
Change desktop file name to include domain name

### PR DESCRIPTION
**Pull request by nicolasfella**
This fixes taskbar and window icon on Wayland

### CODE REVIEW

**Comment by nicolasfella** [comment]
The implicit desktopfilename is com.kdab.hotspot, renaming the desktop file from hotspot.desktop to com.kdab.hotspot.desktop would be another option to fix this

**Comment by milianw** [comment]
I guess the more verbose .desktop file would be the better choice to make it more explicit or what do you think @nicolasfella ?

**Comment by milianw** [comment]
the change to the perfparser submodule is unrelated (or? what did you change there?)

**Review by milianw — CHANGES_REQUESTED** [review]
perfparser changes are unrelated

**Comment by milianw** [comment]
undid the unrelated perfparser change and pushed it - thanks @nicolasfella

**Pull request closed without merging**
