### PR TITLE
Mention gettext dependency in README

### PR DESCRIPTION
**Pull request by suy**

### CODE REVIEW

**Comment by suy** [comment]
I don't have access to any Fedora system, so I don't known the name of the package, sorry.

**Comment by krf** [comment]
We don't have a direct dependency on gettext. Where did you notice the a missing gettext package?

**Comment by suy** [comment]
I got a CMake error about missing msgmerge when compiling hotspot in a "fresh" computer with few development packages installed. That's in the `gettext` package for me. I did not look where the message came from.

**Comment by suy** [comment]
I tried again. This is what I get:

```
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Gettext (missing: GETTEXT_MSGMERGE_EXECUTABLE
  GETTEXT_MSGFMT_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindGettext.cmake:87 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /usr/lib/x86_64-linux-gnu/cmake/KF5I18n/KF5I18NMacros.cmake:28 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/KF5I18n/KF5I18nConfig.cmake:43 (include)
  /usr/share/ECM/find-modules/FindKF5.cmake:74 (find_package)
  CMakeLists.txt:59 (find_package)
```

**Comment by krf** [comment]
Fair enough

**Pull request closed without merging**
